trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 9'
  inputs:
    packageType: sdk
    version: '9.x'

- script: dotnet restore
  displayName: 'Restore dependencies'

- script: dotnet build --no-restore --configuration Release
  displayName: 'Build'
